### ISSUE TITLE
CMake Error: NOTFOUND. HIPBLAS_LIBRARY linked by target "THC" in directory /home/cutorch_hip/lib/THC

### ISSUE THREAD

**Issue by victor-felicitas** [ROCmSoftwarePlatform/cutorch_hip#17]
Hi!

I can't install cutorch due to the error:
CMake Error: NOTFOUND. HIPBLAS_LIBRARY linked by target "THC" in directory /home/vityek/cutorch_hip/lib/THC

I've installed Hipblas, however it seems something is missing...

**Comment by wsttiger** [comment]
Hi, 

At this time, we are no longer supporting cutorch. We should be releasing a ROCM version of PyTorch in the next month or so. Thanks for your interest and patience.
